# Identificando trabalhos acadêmicos que usam dados públicos

In [1]:
from pathlib import Path

import datausage as du

Primeiro, vamos inicializar o sistema que será fixo para todas as classificações. Isso inclui o modelo utilizado e o template do prompt.

In [5]:
# Set OpenAI client and config:
#key_path = '/home/hxavier/ceweb/config/keys/openai-api-key_ceweb_2025-11-14.txt'
key_path = '/home/hxavier/ceweb/config/keys/openai-api-key_2024-06-06.txt'
prompt_path = 'prompts/open-data_llm-template_v10.md'
detector = du.PublicDataUsageDetector('gpt-5', key_path, prompt_path, '', '', project=None)

## UFAM - Amostra 01

In [28]:
# Colocando batch para rodar:
data_file = '../dados/dspaces/samples/tccs-teses-dissertacoes-outros_ufam_2020-2025_n472_s01.csv'
#batch_obj = detector.run_classification(data_file)

In [10]:
# Verificando status da batch:
batch_status = detector.batch_status()

============================================================
BATCH INFORMATION
============================================================

[GENERAL]
------------------------------------------------------------
Batch ID              : batch_69a7264503e88190812a8cb0dcce9336
Description           : PROMPT: open-data_llm-template_v10 / DATA: tccs-teses-dissertacoes-outros_ufam_2020-2025_n472_s01
Model                 : gpt-5-2025-08-07

[TIMESTAMPS]
------------------------------------------------------------
Created at            : 2026-03-03 15:19:49
Completed at          : 2026-03-03 15:33:16

[FILES]
------------------------------------------------------------
Input file            : file-QZuwkieCHWLVXMVybji9Ge
Output file           : file-A1WBtgH3MTX51NvFZESoex

[INSTANCES]
------------------------------------------------------------
Total                 : 472
Completed             : 472
Failed                : 0

[TOKENS]
------------------------------------------------------------
Input tokens          : 445228
Cached input tokens   : 0
Output tokens         : 74820
Reasoning tokens      : 68288
Total tokens          : 520048

============================================================

In [11]:
# Download batch results:
#detector.download_results()

Results from batch batch_69a7264503e88190812a8cb0dcce9336 saved to ../dados/dspaces/samples/tccs-teses-dissertacoes-outros_ufam_2020-2025_n472_s01_gpt-out.jsonl.

In [56]:
# Save results to CSV:
#results_df = du.build_results_csv(data_file, detector.jsonl_in, detector.jsonl_out, du.in2out_name(data_file, out_suffix='gpt-pred', file_extension='.csv'))

## UFCG - Amostra 01

In [3]:
# Colocando batch para rodar:
data_file = '../dados/dspaces/samples/tccs-teses-dissertacoes_ufcg_2020-2025_n569_s01.csv'
batch_obj = detector.run_classification(data_file)

In [7]:
# Verificando status da batch:
batch_status = detector.batch_status()

============================================================
BATCH INFORMATION
============================================================

[GENERAL]
------------------------------------------------------------
Batch ID              : batch_69a89382bd6c8190a264cd6d65ef8960
Description           : PROMPT: open-data_llm-template_v10 / DATA: tccs-teses-dissertacoes_ufcg_2020-2025_n569_s01
Model                 : gpt-5-2025-08-07

[TIMESTAMPS]
------------------------------------------------------------
Created at            : 2026-03-04 17:18:10
Completed at          : 2026-03-04 20:04:20

[FILES]
------------------------------------------------------------
Input file            : file-RyeXZJAkXBqDc4TYhwNfwT
Output file           : file-Mr7xx9yZuN3FJNs4SgMsb9

[INSTANCES]
------------------------------------------------------------
Total                 : 569
Completed             : 569
Failed                : 0

[TOKENS]
------------------------------------------------------------
Input tokens          : 570497
Cached input tokens   : 0
Output tokens         : 92000
Reasoning tokens      : 84160
Total tokens          : 662497

============================================================

In [11]:
# Download batch results:
#detector.download_results()

Results from batch batch_69a89382bd6c8190a264cd6d65ef8960 saved to ../dados/dspaces/samples/tccs-teses-dissertacoes_ufcg_2020-2025_n569_s01_gpt-out.jsonl.

In [96]:
# Save results to CSV:
#results_df = du.build_results_csv(data_file, detector.jsonl_in, detector.jsonl_out, du.in2out_name(data_file, out_suffix='gpt-pred', file_extension='.csv'))

* Ajustar limpeza das bases de dados para retirar \r\n dos títulos

## UFES - Amostra 01

In [7]:
# Colocando batch para rodar:
data_file = '../dados/dspaces/samples/tccs-teses-dissertacoes_ufes_2020-2025_n323_s01.csv'
batch_obj = detector.run_classification(data_file)

In [10]:
# Verificando status da batch:
batch_status = detector.batch_status()

============================================================
BATCH INFORMATION
============================================================

[GENERAL]
------------------------------------------------------------
Batch ID              : batch_69d497105ef481909d1256e4dce7244d
Description           : PROMPT: open-data_llm-template_v10 / DATA: tccs-teses-dissertacoes_ufes_2020-2025_n323_s01
Model                 : gpt-5-2025-08-07
Status                : completed

[TIMESTAMPS]
------------------------------------------------------------
Created at            : 2026-04-07 02:33:04
Completed at          : 2026-04-07 02:36:10

[FILES]
------------------------------------------------------------
Input file            : file-XPWvBivQAE8jdHPYcdxDjH
Output file           : file-Sc9CRf9ATcm2thYiudAbAg

[INSTANCES]
------------------------------------------------------------
Total                 : 323
Completed             : 323
Failed                : 0

[TOKENS]
------------------------------------------------------------
Input tokens          : 330916
Cached input tokens   : 0
Output tokens         : 57448
Reasoning tokens      : 52992
Total tokens          : 388364

============================================================

In [11]:
# Download batch results:
detector.download_results()

Results from batch batch_69d497105ef481909d1256e4dce7244d saved to ../dados/dspaces/samples/tccs-teses-dissertacoes_ufes_2020-2025_n323_s01_gpt-out.jsonl.

In [12]:
# Save results to CSV:
results_df = du.build_results_csv(data_file, detector.jsonl_in, detector.jsonl_out, du.in2out_name(data_file, out_suffix='gpt-pred', file_extension='.csv'))

## UFRGS - Amostra 01 (1/2)

In [13]:
# Colocando batch para rodar:
data_file = '../dados/dspaces/samples/tccs-teses-dissertacoes_ufrgs_2020-2025_n883_s01.csv'
batch_obj = detector.run_classification(data_file)

In [17]:
# Verificando status da batch:
batch_status = detector.batch_status()

============================================================
BATCH INFORMATION
============================================================

[GENERAL]
------------------------------------------------------------
Batch ID              : batch_69ebb90b46948190b42093edb4e4fa28
Description           : PROMPT: open-data_llm-template_v10 / DATA: tccs-teses-dissertacoes_ufrgs_2020-2025_n883_s01
Model                 : gpt-5-2025-08-07
Status                : completed

[TIMESTAMPS]
------------------------------------------------------------
Created at            : 2026-04-24 15:40:11
Completed at          : 2026-04-24 15:44:45

[FILES]
------------------------------------------------------------
Input file            : file-L6LFMXGdwaw4FBHixRvapP
Output file           : file-Mh64s97NotEA1VGZDA7375

[INSTANCES]
------------------------------------------------------------
Total                 : 883
Completed             : 883
Failed                : 0

[TOKENS]
------------------------------------------------------------
Input tokens          : 853666
Cached input tokens   : 0
Output tokens         : 144609
Reasoning tokens      : 132480
Total tokens          : 998275

============================================================

In [18]:
# Download batch results:
detector.download_results()

Results from batch batch_69ebb90b46948190b42093edb4e4fa28 saved to ../dados/dspaces/samples/tccs-teses-dissertacoes_ufrgs_2020-2025_n883_s01_gpt-out.jsonl.

In [19]:
# Save results to CSV:
results_df = du.build_results_csv(data_file, detector.jsonl_in, detector.jsonl_out, du.in2out_name(data_file, out_suffix='gpt-pred', file_extension='.csv'))

In [21]:
results_df['y_pred'].mean()

np.float64(0.13250283125707815)

In [22]:
results_df

,autoria,orientador,titulo,ano,fomento,publicador,local,tipo,programa,nivel,paginas,resumo,idioma,uri,palavras_chave,gpt_id_in,gpt_titulo,class,y_pred
0,"Stradolini, William Dutra","Pastorio, Dioni Paulo",Os currículos dos Cursos Pré vestibulares popu...,2024,NaN,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Dissertação,Programa de Pós-Graduação em Ensino de Física,Mestrado,193 p.,Os Cursos Pré-Vestibulares Populares são inici...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Ciências da natureza; Currículo; Curso pré-ves...,request-0,Os currículos dos Cursos Pré vestibulares popu...,Does not use public data,0
1,"Dorneles, Lucas de Britto","Santos, Cristiane Pizzutti dos","Na dúvida, não compartilhe: o papel da consequ...",2021,NaN,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Dissertação,Programa de Pós-Graduação em Administração,Mestrado,[ca. 84] f.,O modo como a informação é consumida vem mudan...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Compartilhamento de informação; Notícias; Rede...,request-1,"Na dúvida, não compartilhe: o papel da consequ...",Does not use public data,0
2,"Ribeiro, Luisa Alem","Tatsch, Ana Lucia",Inova Saúde: uma análise à luz da perspectiva ...,2021,CAPES,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Dissertação,Programa de Pós-Graduação em Economia,Mestrado,154 fl.,O Complexo Econômico-Industrial da Saúde (CEIS...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Programa Inova Saúde; Inovação; Política; Saúd...,request-2,Inova Saúde: uma análise à luz da perspectiva ...,Does not use public data,0
3,"Santos, Dhietelly Morghana Almeida","Sperrhake, Renata",Avaliações externas estaduais da alfabetização...,2022,NaN,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Trabalho de conclusão de curso,Licenciatura em Pedagogia,Graduação,94 f.,O presente trabalho se propôs a mapear e carac...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Alfabetização; Avaliação da educação; Educação,request-3,Avaliações externas estaduais da alfabetização...,Does not use public data,0
4,"Doná, Fernanda Liell Bech","Storck, Alfredo Carlos",A querela dos universais: de porfírio a Abelardo,2025,NaN,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Trabalho de conclusão de curso,Bacharelado em Filosofia,Graduação,43 f.,O seguinte trabalho busca fazer uma apresentaç...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,"Boécio; Abelardo, Pedro; Filosofia; Neoplatoni...",request-4,A querela dos universais: de porfírio a Abelardo,Does not use public data,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,"Nunes, Tassiana Fiorese","Perlin, Marcelo Scherer",Finanças pessoais: o impacto da reserva de eme...,2021,NaN,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Trabalho de conclusão de curso,Curso de Administração,Graduação,46 f.,Considerando o cenário pandêmico atípico que a...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Conhecimento financeiro; Educação financeira; ...,request-878,Finanças pessoais: o impacto da reserva de eme...,Does not use public data,0
879,"Carpes, Larissa Salomoni","Crispim, Daisy",Permeabilidade intestinal em indivíduos com do...,2020,NaN,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Dissertação,"Programa de Pós-Graduação em Alimentação, Nutr...",Mestrado,62 f.,Introdução: A permeabilidade intestinal é uma ...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Biomarcadores; Diabetes mellitus; Insuficiênci...,request-879,Permeabilidade intestinal em indivíduos com do...,Does not use public data,0
880,"Lima, Alana dos Reis","Perondi, Maurício",O método pedagógico desenvolvido no movimento ...,2024,NaN,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Trabalho de conclusão de curso,Licenciatura em Pedagogia,Graduação,38 f.,O presente trabalho apresenta o método pedagóg...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Educação não-formal; Ensino; Jovens; Pedagogia...,request-880,O método pedagógico desenvolvido no movimento ...,Uses public data,1
881,"Knebel, Melissa Dadalt","Mariath, Adriela Azevedo Souza",Diagnóstico e intervenções terapêuticas da anq...,2025,NaN,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Trabalho de conclusão de curso,Curso de Odontologia,Graduação,37f.,Introdução: A anquiloglossia é uma alteração c...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Amamentação; Anquiloglossia; Diagnóstico; Inte...,request-881,Diagnóstico e intervenções terapêuticas da anq...,Uses public data,1
882,"Mencucini, Paula Sousa França","Pereira, Leonardo Régis Leira",Perfil farmacoterapêutico de pacientes com epi...,2020,NaN,Universidade Federal do Rio Grande do Sul,"Porto Alegre, BR-RS",Dissertação,Programa de Pós-Graduação em Assistência Farma...,Mestrado,91 p.,Introdução: A administração dos fármacos antie...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Acesso aos serviços de saúde; Adesão à medicaç...,request-882,Perfil farmacoterapêutico de pacientes com epi...,Does not use public data,0

## UFRGS - Amostra 01 (2/2)

In [23]:
# Colocando batch para rodar:
data_file = '../dados/dspaces/samples/tccs-teses-dissertacoes_ufrgs_2020-2025_n883_s02.csv'
batch_obj = detector.run_classification(data_file)

In [25]:
# Verificando status da batch:
batch_status = detector.batch_status()

============================================================
BATCH INFORMATION
============================================================

[GENERAL]
------------------------------------------------------------
Batch ID              : batch_69ebc21fc44081909aaa8d12a8b088e6
Description           : PROMPT: open-data_llm-template_v10 / DATA: tccs-teses-dissertacoes_ufrgs_2020-2025_n883_s02
Model                 : gpt-5-2025-08-07
Status                : completed

[TIMESTAMPS]
------------------------------------------------------------
Created at            : 2026-04-24 16:18:55
Completed at          : 2026-04-24 16:24:31

[FILES]
------------------------------------------------------------
Input file            : file-JcisVVaSjJyRPB5aMRiL6f
Output file           : file-4daHYbv49r6WpSNZYKDunp

[INSTANCES]
------------------------------------------------------------
Total                 : 883
Completed             : 883
Failed                : 0

[TOKENS]
------------------------------------------------------------
Input tokens          : 835608
Cached input tokens   : 0
Output tokens         : 153201
Reasoning tokens      : 141056
Total tokens          : 988809

============================================================

In [26]:
# Download batch results:
detector.download_results()

Results from batch batch_69ebc21fc44081909aaa8d12a8b088e6 saved to ../dados/dspaces/samples/tccs-teses-dissertacoes_ufrgs_2020-2025_n883_s02_gpt-out.jsonl.

In [41]:
# Save results to CSV:
results_df = du.build_results_csv(data_file, detector.jsonl_in, detector.jsonl_out, du.in2out_name(data_file, out_suffix='gpt-pred', file_extension='.csv'))

In [42]:
results_df['y_pred'].mean()

np.float64(0.11551528878822197)

In [43]:
results_df

,autoria,orientador,titulo,ano,fomento,publicador,local,tipo,programa,nivel,paginas,resumo,idioma,uri,palavras_chave,gpt_id_in,gpt_titulo,class,y_pred
0,"Rossa, Aline Severo","Giovanaz, Marlise Maria",Acervos submersos: o que as enchentes de 2024 ...,2025,NaN,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Trabalho de conclusão de curso,Curso de Biblioteconomia,Graduação,53 f.,Esta pesquisa analisa a relação entre as enche...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Acervo bibliográfico; Acervo museológico; Muda...,request-0,Acervos submersos: o que as enchentes de 2024 ...,Does not use public data,0
1,"Brito, Matheus Bittencourt de","Herrlein Junior, Ronaldo",Dívida pública: a base da financeirização no B...,2021,CAPES,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Dissertação,Programa de Pós-Graduação em Economia,Mestrado,125 fl.,O processo de financeirização da economia é um...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Dívida pública; Financeirização; Brasil; Economia,request-1,Dívida pública: a base da financeirização no B...,Does not use public data,0
2,"Cuppini, Marla","Collares, Fabrício Mezzomo",Utilização de sistemas carreadores de fármacos...,2021,NaN,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Tese,Programa de Pós-Graduação em Odontologia/Área ...,Doutorado,67 f.,O objetivo do presente estudo foi avaliar as p...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Amoxicilina; Bioatividades; Indometacina; Micr...,request-2,Utilização de sistemas carreadores de fármacos...,Does not use public data,0
3,"Squeff, Bernardo Affonso","Rossi, Rodrigo",Calibração de um modelo de dano usando ensaios...,2021,NaN,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Trabalho de conclusão de curso,Curso de Engenharia Mecânica,Graduação,21 f.,A motivação do tema do trabalho a ser desenvol...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Dano dúctil; Ensaios de tração; Engenharia mec...,request-3,Calibração de um modelo de dano usando ensaios...,Does not use public data,0
4,"Giongo, Marina Anderle","Linden, Júlio Carlos de Souza van der",Princípios de colaboração para o design de mod...,2020,NaN,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Tese,Programa de Pós-Graduação em Design,Doutorado,182 f.,Inovação e sustentabilidade são muito favoreci...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Design; Moda sustentável; Engenharia de produção,request-4,Princípios de colaboração para o design de mod...,Does not use public data,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,"Nascimento, Yan Alencar Pereira do","Trein, Sérgio Roberto",We are here and we are queer: a diversidade ...,2024,NaN,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Trabalho de conclusão de curso,Curso de Publicidade e Propaganda,Graduação,[81] f.,A forma a qual a comunidade LGBTQIAPN+ é repre...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Estudos de gênero; LGBTQIAP+; Representativida...,request-878,We are here and we are queer: a diversidade ...,Does not use public data,0
879,"Carvalho, Quênia de","Rosa, Adriane Ribeiro",Validação da escala P-Weight em população adul...,2023,NaN,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Dissertação,Programa de Pós-Graduação em Ciências Biológic...,Mestrado,118 f.,Objetivo: O objetivo é analisar as propriedade...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Entrevista motivacional; Estudos de intervençã...,request-879,Validação da escala P-Weight em população adul...,Does not use public data,0
880,"Marques Neto, Nery da Silva","Fernandes, Pedro Rafael Bolognese",Desenvolvimento e teste de plataforma de comun...,2020,NaN,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Trabalho de conclusão de curso,Curso de Engenharia de Controle e Automação,Graduação,43 f.,"Ao longo das últimas décadas, os sistemas supe...",Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Desenvolvimento de software; Engenharia de con...,request-880,Desenvolvimento e teste de plataforma de comun...,Does not use public data,0
881,"Camargo, Luisa Nadal","Vasconcellos, Cesar Augusto Zen",Neutrino oscillation in non-commutative spacetime,2025,CAPES,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Dissertação,Programa de Pós-Graduação em Física,Mestrado,"vi, 69 p.",Os neutrinos são encontrados na natureza com t...,Inglês,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Campos magnéticos; Neutrinos; Oscilações de ne...,request-881,Neutrino oscillation in non-commutative spacetime,Does not use public data,0
882,"Machado, Gabriel Pizzio","Diehl, Nicolau Matiel Lunardi",Regularidade fina para equação de meios porosos,2023,NaN,Universidade Federal do Rio Grande do Sul - UFRGS,"Porto Alegre, BR-RS",Dissertação,Programa de Pós-Graduação em Matemática,Mestrado,40 f.,A teoria de regularidade de soluções de equaçõ...,Português,http://www.bibliotecadigital.ufrgs.br/da.php?n...,Equações; Equações parabólicas; Iteração geomé...,request-882,Regularidade fina para equação de meios porosos,Does not use public data,0